# workflow的名称，会显示在工作流运行页面
name: todo-s-ci

# 工作流执行的契机：push表示每次push代码之后都会执行
on:
  push:
    branches:
      - master

jobs:
  build:
    # 构建运行的环境
    runs-on: ubuntu-latest
    # 构建步骤
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: '16.15'
      - run: npm install
      - name: 生成dist
        run: npm run build
      - name: 生成.env文件
        run: |
          echo -e "ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }}\n
            ACCESS_KEY_SECRET=${{ secrets.ACCESS_KEY_SECRET }}\n
            SQL_HOST=${{ secrets.SQL_HOST }}\n
            SQL_PORT=3306\n
            SQL_USERNAME=${{ secrets.SQL_USERNAME }}\n
            SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}\n
            SQL_DATABASE=todo" > .env
      - name: 打印.env文件
        run: cat .env
      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-chengdu.aliyuncs.com
          username: "${{ secrets.ALI_ACR_USERNAME }}"
          password: "${{ secrets.ALI_ACR_PASSWORD }}"
      - name: Build and push image
        run: |
          docker build -t registry.cn-chengdu.aliyuncs.com/${{ secrets.ALI_ACR_USERNAME }}/todo-s:latest .
          docker push registry.cn-chengdu.aliyuncs.com/${{ secrets.ALI_ACR_USERNAME }}/todo-s:latest

